# version format.  This will always be changed by the Install script.
version: 1.0.{build}

# Dev14 is required to build (os actually means VM image)
os: Visual Studio 2015 Preview

# set up the build number (last two numbers).  this has to happen before
# we do anything else because it's the only time we can set environment
# variables.
init:
  - ps: $year = (Get-Date -Format 'yyyy').Substring(3,1)
  - ps: $day = Get-Date -Format 'MMdd'
  - ps: $buildVersion = $year + $day + '.' + $env:APPVEYOR_BUILD_NUMBER
  - ps: Add-AppveyorMessage -Message "Updating build number to $buildVersion" -Category Information
  - ps: Set-AppveyorBuildVariable -Name BuildNumber -Value $buildVersion

install:
  - cmd: powershell -ExecutionPolicy Bypass scripts\Appveyor-Install.ps1

before_build:
  - nuget restore

build:
  project: Salesforce.VisualStudio.Services.sln
  
configuration:
  - Release
  - Debug
  
platform: Any CPU

artifacts:
  - path: src\Salesforce.VisualStudio.Services\bin\$(configuration)\Salesforce.VisualStudio.Services.vsix
    name: $(configuration) VSIX
  - path: src\Salesforce.VisualStudio.Services\bin\$(configuration)\Salesforce.VisualStudio.Services.pdb
    name: $(configuration) PDB